In [6]:
import pandas as pd

In [7]:
혼잡도 = pd.read_csv("혼잡도_2223_updated_속성변경.csv")
역특징 = pd.read_csv("지하철_특징별_혼잡도역명반영.csv", encoding = 'euc-kr')
display(혼잡도, 역특징)

,Unnamed: 0,연월일시,호선,역번호,역명,상하구분,AWS지점코드,기온,풍향,풍속,...,상대습도,체감온도,혼잡도,year,month,day,hour,datetime,nx,ny
0,0,2022010100,1,150,서울역,상선,419,-9.4,61.0,3.5,...,34.0,-12.8,0,2022,1,1,0,2022-01-01 00:00:00,60.0,126.0
1,1,2022010101,1,150,서울역,상선,419,-9.4,39.4,2.0,...,35.8,-10.4,0,2022,1,1,1,2022-01-01 01:00:00,60.0,126.0
2,2,2022010105,1,150,서울역,상선,419,-9.7,350.9,0.9,...,44.5,-10.8,2,2022,1,1,5,2022-01-01 05:00:00,60.0,126.0
3,3,2022010106,1,150,서울역,상선,419,-9.4,139.6,0.5,...,43.4,-11.0,5,2022,1,1,6,2022-01-01 06:00:00,60.0,126.0
4,4,2022010107,1,150,서울역,상선,419,-10.1,173.6,2.7,...,49.2,-10.9,4,2022,1,1,7,2022-01-01 07:00:00,60.0,126.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11607866,11607866,2023123119,8,2828,남위례,하선,572,0.6,0.0,0.0,...,83.1,0.0,18,2023,12,31,19,2023-12-31 19:00:00,63.0,124.0
11607867,11607867,2023123120,8,2828,남위례,하선,572,0.0,354.7,0.0,...,84.7,-0.6,17,2023,12,31,20,2023-12-31 20:00:00,63.0,124.0
11607868,11607868,2023123121,8,2828,남위례,하선,572,-0.6,0.0,0.0,...,85.1,-1.1,21,2023,12,31,21,2023-12-31 21:00:00,63.0,124.0
11607869,11607869,2023123122,8,2828,남위례,하선,572,-0.8,0.0,0.0,...,85.6,-1.3,18,2023,12,31,22,2023-12-31 22:00:00,63.0,124.0
11607870,11607870,2023123123,8,2828,남위례,하선,572,-1.3,110.7,0.1,...,85.6,-1.9,22,2023,12,31,23,2023-12-31 23:00:00,63.0,124.0

,지하철역ID,지하철호선ID,역명,지하철호선명,환승역여부,지상/지하,이전지하철역ID,이전지하철역명,다음지하철역ID,다음지하철역명,...,강남권/비강남권,구/동,환승호선수,지하철역X좌표,지하철역Y좌표,연계역번호,지하철역코드,급행정차여부(0:미정차/1:상행정차/2:하행정차/3:양방향정차),위도,경도
0,1001000100,1001,소요산,1,X,NaN,1001001001,청산,1001000101,동두천,...,-,상봉암동,1,205362.3891,494245.6421,100,190,3.0,NaN,NaN
1,1001000101,1001,동두천,1,X,NaN,1001000100,소요산,1001000102,보산,...,-,동두천동,1,204824.7370,492006.4241,101,189,3.0,NaN,NaN
2,1001000102,1001,보산,1,X,NaN,1001000101,동두천,1001000103,동두천중앙,...,-,보산동,1,205021.9647,490533.9431,102,188,0.0,NaN,NaN
3,1001000103,1001,동두천중앙,1,X,NaN,1001000102,보산,1001000104,지행,...,-,생연2동,1,204967.7474,489106.9743,103,187,3.0,NaN,NaN
4,1001000104,1001,지행,1,X,NaN,1001000103,동두천중앙,1001000105,덕정,...,-,지행동,1,204914.1407,488082.7877,104,186,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
406,1008000823,1008,남한산성입구,8,X,지하,1008000822,산성,1008000824,단대오거리,...,-,수정구,1,214151.5888,439152.2517,823,13,0.0,37.451568,127.159845
407,1008000824,1008,단대오거리,8,X,지하,1008000823,남한산성입구,1008000825,신흥,...,-,수정구,1,213874.1780,438439.8257,824,14,0.0,37.445057,127.156735
408,1008000825,1008,신흥,8,X,지하,1008000824,단대오거리,1008000826,수진,...,-,수정구,1,213066.3813,437968.0179,825,15,0.0,37.440952,127.147590
409,1008000826,1008,수진,8,X,지하,1008000825,신흥,1008000827,모란,...,-,수정구,1,212457.0371,437601.3677,826,16,0.0,37.437575,127.140936
410,1008000827,1008,모란,8,O,지하,1008000826,수진,1008000827,모란,...,-,중원구,2,211505.0278,437183.4257,827,17,0.0,37.433888,127.129921

In [8]:
역특징.rename(columns= {"지하철호선명":"호선"}, inplace=True)
역특징.head()

,지하철역ID,지하철호선ID,역명,호선,환승역여부,지상/지하,이전지하철역ID,이전지하철역명,다음지하철역ID,다음지하철역명,...,강남권/비강남권,구/동,환승호선수,지하철역X좌표,지하철역Y좌표,연계역번호,지하철역코드,급행정차여부(0:미정차/1:상행정차/2:하행정차/3:양방향정차),위도,경도
0,1001000100,1001,소요산,1,X,NaN,1001001001,청산,1001000101,동두천,...,-,상봉암동,1,205362.3891,494245.6421,100,190,3.0,NaN,NaN
1,1001000101,1001,동두천,1,X,NaN,1001000100,소요산,1001000102,보산,...,-,동두천동,1,204824.7370,492006.4241,101,189,3.0,NaN,NaN
2,1001000102,1001,보산,1,X,NaN,1001000101,동두천,1001000103,동두천중앙,...,-,보산동,1,205021.9647,490533.9431,102,188,0.0,NaN,NaN
3,1001000103,1001,동두천중앙,1,X,NaN,1001000102,보산,1001000104,지행,...,-,생연2동,1,204967.7474,489106.9743,103,187,3.0,NaN,NaN
4,1001000104,1001,지행,1,X,NaN,1001000103,동두천중앙,1001000105,덕정,...,-,지행동,1,204914.1407,488082.7877,104,186,0.0,NaN,NaN

In [9]:
import pandas as pd

# '역명'과 '호선' 열을 기준으로 병합
merged_혼잡도_역특징 = pd.merge(혼잡도, 역특징, on=['역명', '호선'], how='inner')  # inner, left, right, outer 선택 가능

# 결과 저장 (필요시)
merged_혼잡도_역특징.to_csv('merged_혼잡도_역특징_updated.csv', index=False)

In [10]:
merged_혼잡도_역특징.head()

,Unnamed: 0,연월일시,호선,역번호,역명,상하구분,AWS지점코드,기온,풍향,풍속,...,강남권/비강남권,구/동,환승호선수,지하철역X좌표,지하철역Y좌표,연계역번호,지하철역코드,급행정차여부(0:미정차/1:상행정차/2:하행정차/3:양방향정차),위도,경도
0,0,2022010100,1,150,서울역,상선,419,-9.4,61.0,3.5,...,비강남권,동자동,4,197529.9154,450688.4645,133,240,3.0,37.55315,126.972533
1,1,2022010101,1,150,서울역,상선,419,-9.4,39.4,2.0,...,비강남권,동자동,4,197529.9154,450688.4645,133,240,3.0,37.55315,126.972533
2,2,2022010105,1,150,서울역,상선,419,-9.7,350.9,0.9,...,비강남권,동자동,4,197529.9154,450688.4645,133,240,3.0,37.55315,126.972533
3,3,2022010106,1,150,서울역,상선,419,-9.4,139.6,0.5,...,비강남권,동자동,4,197529.9154,450688.4645,133,240,3.0,37.55315,126.972533
4,4,2022010107,1,150,서울역,상선,419,-10.1,173.6,2.7,...,비강남권,동자동,4,197529.9154,450688.4645,133,240,3.0,37.55315,126.972533

In [12]:
pd.set_option('display.max_columns', 50)

In [13]:
merged_혼잡도_역특징.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11496445 entries, 0 to 11496444
Data columns (total 45 columns):
 #   Column                               Dtype
---  ------                               -----
 0   Unnamed: 0                           int64
 1   연월일시                                 int64
 2   호선                                   int64
 3   역번호                                  int64
 4   역명                                   object
 5   상하구분                                 object
 6   AWS지점코드                              int64
 7   기온                                   float64
 8   풍향                                   float64
 9   풍속                                   float64
 10  일강수량                                 float64
 11  시간강수량                                float64
 12  상대습도                                 float64
 13  체감온도                                 float64
 14  혼잡도                                  int64
 15  year                                 int64
 16  month                                int64
 17  day                                  int64
 18  hour                                 int64
 19  datetime                             object
 20  nx                                   float64
 21  ny                                   float64
 22  지하철역ID                               int64
 23  지하철호선ID                              int64
 24  환승역여부                                object
 25  지상/지하                                object
 26  이전지하철역ID                             int64
 27  이전지하철역명                              object
 28  다음지하철역ID                             int64
 29  다음지하철역명                              object
 30  우편번호                                 float64
 31  기본주소                                 object
 32  상세주소                                 object
 33  도/시/군                                object
 34  구                                    object
 35  강남권/비강남권                             object
 36  구/동                                  object
 37  환승호선수                                int64
 38  지하철역X좌표                              float64
 39  지하철역Y좌표                              float64
 40  연계역번호                                object
 41  지하철역코드                               int64
 42  급행정차여부(0:미정차/1:상행정차/2:하행정차/3:양방향정차)  float64
 43  위도                                   float64
 44  경도                                   float64
dtypes: float64(15), int64(16), object(14)
memory usage: 3.9+ GB

In [16]:
merged_혼잡도_역특징.isnull().sum()

Unnamed: 0                                   0
연월일시                                         0
호선                                           0
역번호                                          0
역명                                           0
상하구분                                         0
AWS지점코드                                      0
기온                                       27106
풍향                                       33100
풍속                                       29706
일강수량                                     49416
시간강수량                                    50938
상대습도                                     28004
체감온도                                        22
혼잡도                                          0
year                                         0
month                                        0
day                                          0
hour                                         0
datetime                                     0
nx                                           0
ny                                           0
지하철역ID                                       0
지하철호선ID                                      0
환승역여부                                        0
지상/지하                                  3115181
이전지하철역ID                                     0
이전지하철역명                                      0
다음지하철역ID                                     0
다음지하철역명                                      0
우편번호                                     30030
기본주소                                         0
상세주소                                    942101
도/시/군                                        0
구                                            0
강남권/비강남권                                     0
구/동                                          0
환승호선수                                        0
지하철역X좌표                                  32046
지하철역Y좌표                                  32046
연계역번호                                        0
지하철역코드                                       0
급행정차여부(0:미정차/1:상행정차/2:하행정차/3:양방향정차)       2016
위도                                     3175241
경도                                     3175241
dtype: int64

In [1]:
import pandas as pd

In [2]:
혼잡도 = pd.read_csv("혼잡도_2223_updated_속성변경.csv")
혼잡도

,Unnamed: 0,연월일시,호선,역번호,역명,상하구분,AWS지점코드,기온,풍향,풍속,...,상대습도,체감온도,혼잡도,year,month,day,hour,datetime,nx,ny
0,0,2022010100,1,150,서울역,상선,419,-9.4,61.0,3.5,...,34.0,-12.8,0,2022,1,1,0,2022-01-01 00:00:00,60.0,126.0
1,1,2022010101,1,150,서울역,상선,419,-9.4,39.4,2.0,...,35.8,-10.4,0,2022,1,1,1,2022-01-01 01:00:00,60.0,126.0
2,2,2022010105,1,150,서울역,상선,419,-9.7,350.9,0.9,...,44.5,-10.8,2,2022,1,1,5,2022-01-01 05:00:00,60.0,126.0
3,3,2022010106,1,150,서울역,상선,419,-9.4,139.6,0.5,...,43.4,-11.0,5,2022,1,1,6,2022-01-01 06:00:00,60.0,126.0
4,4,2022010107,1,150,서울역,상선,419,-10.1,173.6,2.7,...,49.2,-10.9,4,2022,1,1,7,2022-01-01 07:00:00,60.0,126.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11607866,11607866,2023123119,8,2828,남위례,하선,572,0.6,0.0,0.0,...,83.1,0.0,18,2023,12,31,19,2023-12-31 19:00:00,63.0,124.0
11607867,11607867,2023123120,8,2828,남위례,하선,572,0.0,354.7,0.0,...,84.7,-0.6,17,2023,12,31,20,2023-12-31 20:00:00,63.0,124.0
11607868,11607868,2023123121,8,2828,남위례,하선,572,-0.6,0.0,0.0,...,85.1,-1.1,21,2023,12,31,21,2023-12-31 21:00:00,63.0,124.0
11607869,11607869,2023123122,8,2828,남위례,하선,572,-0.8,0.0,0.0,...,85.6,-1.3,18,2023,12,31,22,2023-12-31 22:00:00,63.0,124.0
11607870,11607870,2023123123,8,2828,남위례,하선,572,-1.3,110.7,0.1,...,85.6,-1.9,22,2023,12,31,23,2023-12-31 23:00:00,63.0,124.0

In [8]:
역명체크_혼잡도파일 = pd.DataFrame(혼잡도['역명'].unique(), columns=['역명'])
역명체크_혼잡도파일.to_excel("역명체크_혼잡도파일.xlsx")